package org.academic;

public enum Events {
    SEMESTER_START,COURSE_FLOAT_START,COURSE_FLOAT_END,COURSE_REGISTRATION_START,COURSE_REGISTRATION_END,GRADE_SUBMISSION_START,GRADE_SUBMISSION_END,SEMESTER_END
}
